### ISSUE TITLE
Getting error,Chromedriver executable  needs to be in PATH

### ISSUE THREAD

**Issue by rsoorajs** [bestmatteo/Telegram-Bot#2]
i am on ubuntu,using python3.

while running python3 setup.py

it popup and error about the `chrome driver`
can you tell how to fix this.

error name `Chromedriver executable needs to be in PATH `

**Comment by telegrambotdev** [comment]
![IMG20200709101059](https://user-images.githubusercontent.com/20116017/86998933-14d33b00-c1cf-11ea-8893-bf6a0aa5c339.jpg)

**Comment by rsoorajs** [comment]
![Screenshot from 2020-07-08 20-49-09](https://user-images.githubusercontent.com/20116017/86999015-41875280-c1cf-11ea-9861-adde8b09eb6f.png)
![Screenshot from 2020-07-08 20-58-29](https://user-images.githubusercontent.com/20116017/86999018-42b87f80-c1cf-11ea-94b3-3ab770a9600d.png)

**Comment by rsoorajs** [comment]
try to make releases for linux and windows.that will be much easier.

and could you tell me how to solve the above problem ?

**Comment by rsoorajs** [comment]
fixed.
kindly update the readme,because we need to download the chromedriver manually for ubuntu
